# app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    security/critical-cve: "false"
    security/last-scan: "2026-05-06"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.6.0.190:80/proxy/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html  # nginx sert les fichiers depuis ce dossier
      volumes:
      - name: html
        configMap:
          name: nginx-html  # on monte le ConfigMap comme un dossier
